#!/usr/bin/env node
// `make docs`: builds docs/website from the widget's own sources. The page
// runs the studio in the browser: settings from Schema.js, looks from
// Looks.js, charts through the widget's fragment shader (qsb's GLSL ES
// variant), all converted here, so the site cannot drift from the widget.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ui = path.join(root, "package/contents/ui");
const site = path.join(root, "docs/website");

// QML JavaScript libraries: drop the .pragma/.import lines and evaluate each
// with its imports supplied as globals.
function load(file, globals = {}) {
    const code = fs.readFileSync(path.join(ui, file), "utf8").replace(/^\.(pragma|import).*$/gm, "");
    const context = vm.createContext({ ...globals });
    vm.runInContext(code, context);
    return context;
}
const Catalog = load("studio/StudioCatalog.js");
const metadata = JSON.parse(fs.readFileSync(path.join(root, "package/metadata.json"), "utf8"));
const Project = load("studio/ProjectInfo.js", { Funding: load("studio/ProjectFunding.js"), License: load("studio/ProjectLicense.js"), Version: load("studio/ProjectVersion.js") });

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const version = metadata.KPlugin.Version;
const repo = Project.repository;
const store = Project.store;

const defaultsXml = fs.readFileSync(path.join(root, "package/contents/config/main.xml"), "utf8");
const defaults = {};
for (const m of defaultsXml.matchAll(/<entry\s+name="([^"]+)"\s+type="([^"]+)"\s*>\s*<default>([^<]*)<\/default>/g))
    defaults[m[1]] = m[2] === "Bool" ? m[3] === "true" : m[2] === "Int" || m[2] === "Double" ? Number(m[3]) : m[3];

// Page layout after the Plasma Audio Visualizer site: a Looks page with live
// preset cards and a Studio Lab page; both are filled in by app.js.
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Glassy System Monitor — Looks &amp; Studio</title>
<meta name="description" content="${esc(metadata.KPlugin.Description)}">
<link rel="icon" type="image/png" href="assets/studio/icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="assets/studio/wallpapers.css">
<link rel="stylesheet" href="glassy.css">
</head>
<body>
<!-- Generated by tools/build_site.mjs (make docs). Edit the generator, not this file. -->
<svg width="0" height="0" style="position:absolute" aria-hidden="true"><filter id="lgRefract" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency="0.006 0.011" numOctaves="2" seed="4" result="n"/><feGaussianBlur in="n" stdDeviation="2.5" result="nb"/><feDisplacementMap in="SourceGraphic" in2="nb" scale="36" xChannelSelector="R" yChannelSelector="G"/></filter></svg>
<header><div class="hwrap">
  <div class="brand"><img class="brand-icon" src="assets/studio/icon.png" width="36" height="36" alt="">Glassy System Monitor</div>
  <nav class="jump" aria-label="Main navigation">
    <a href="#" data-page="looks" aria-current="page">Looks</a>
    <a href="#" data-page="studio">Studio Lab <span class="studio-version">v${esc(version)}</span></a>
    <a href="${repo}" target="_blank" rel="noopener" class="nav-gh" title="Give a star on GitHub if it brings you joy">GitHub <span aria-hidden="true">☆</span> <span class="star-count" data-count="stars">—</span></a>
    <a href="${store}" target="_blank" rel="noopener">KDE Store</a>
  </nav>
</div></header>

<main>
<div data-page="looks">
<section class="hero">
  <div class="hero-bg bd bd-dusk"></div>
  <div class="hero-glow"></div>
  <div class="hero-grid">
    <div class="hero-copy">
      <div class="eyebrow">System monitor for Plasma &amp; Hyprland</div>
      <h1>Your system,<br><span>in glass.</span></h1>
      <p>CPU, memory, network, ping, disks, GPU, sensors and power in one widget — any sections, in any order, side by side. Charts are drawn by a fragment shader on the GPU; this page runs that same shader in your browser.</p>
      <div class="hero-cta">
        <a class="primary-link" href="#looks">Start from a look</a>
        <a class="ghost-link" href="#" data-page="studio">Open the studio →</a>
        <a class="ghost-link star-link" href="${repo}" target="_blank" rel="noopener"><span>GitHub</span><span aria-hidden="true">☆</span> <span class="star-count" data-count="stars">—</span></a>
        <a class="ghost-link" href="${store}" target="_blank" rel="noopener">KDE Store</a>
      </div>
      <div class="stats download-stats" aria-label="Project downloads">
        <a class="stat-item" href="${store}" target="_blank" rel="noopener"><b data-count="kde">—</b>KDE Store downloads</a>
        <a class="stat-item" href="${repo}/releases" target="_blank" rel="noopener"><b data-count="downloads">—</b>GitHub downloads</a>
      </div>
      <p class="star-note">If it brings you joy, <a href="${repo}" target="_blank" rel="noopener">give it a star on GitHub 💙</a>.</p>
    </div>
    <div class="hero-showcase">
      <div class="hero-card">
        <span class="hero-badge"><i></i>Live preview</span>
        <div class="bd bd-sea"></div>
        <div class="fit" id="heroFit"><div class="fi" id="heroFi"></div></div>
      </div>
    </div>
  </div>
</section>

<div class="sh" id="looks"><div><div class="eyebrow">01 · Start from a look</div><h2>Presets</h2></div><p>One click sets the studio. Every card is the widget itself, drawn live with demo data.</p></div>
<section class="presets" id="presets" aria-label="Preset looks"></section>
</div>

<div data-page="studio" hidden>
<div class="sh" id="studio"><div><div class="eyebrow">02 · Tune every detail</div><h2>Settings that preview as you go</h2></div><p>The widget's own settings studio: tabs, search, visual pickers, and the widget always in view — on a desktop or in a panel.</p></div>
<section class="studio">
  <div class="panel" id="panel">
    <div class="phead">
      <label class="search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="search" type="search" placeholder="Search settings…" aria-label="Search settings"><kbd>/</kbd></label>
      <div class="seg" id="envPicker" role="group" aria-label="Desktop"><button data-env="kde" aria-pressed="true">Plasma</button><button data-env="hypr">Hyprland</button></div>
    </div>
    <div class="tabs" role="tablist" id="tabs"></div>
    <div class="pbody" id="pbody"></div>
  </div>

  <div class="stagecol">
    <div class="stage" id="stage">
      <div class="bd bd-sea" id="stageBd"></div>
      <div class="bar top">
        <div class="chip" id="bdPicker"><span class="lbl">Wallpaper</span></div>
        <div class="chip" id="formPicker"><span class="lbl">Show as</span><button data-form="widget" aria-pressed="true">Desktop widget</button><button data-form="panel">Panel</button></div>
      </div>
      <div class="scaler" id="scaler"><div class="scaled" id="mainWidget"></div></div>
      <div class="bar bottom">
        <span></span>
        <span class="sizeinfo" id="sizeInfo"></span>
        <div class="chip" id="zoomPicker"><button data-z="1">1×</button><button data-z="2">2×</button><button data-z="fit" aria-pressed="true">Fit</button></div>
      </div>
    </div>
    <div class="caption">
      <div class="ct"><h3 id="cfgTitle">Changed settings</h3><div class="btnrow"><button class="ghost" id="resetAll">Reset to defaults</button><button class="ghost" id="copyLook">Copy look</button><button class="primary" id="copyCfg">Copy config</button></div></div>
      <div class="cfg" id="cfg"></div>
      <div class="legend"><span><span class="kv" style="padding:1px 6px">key</span> main.xml setting</span><span><span class="kv ishypr" style="padding:1px 6px"><b>key</b></span> Hyprland shell</span></div>
    </div>
  </div>
</section>
</div>
</main>
<footer>
  <span>Glassy System Monitor ${esc(version)} · ${esc(Project.license)} · <a href="${repo}" target="_blank" rel="noopener">GitHub</a> · <a href="${store}" target="_blank" rel="noopener">KDE Store</a></span>
  <span>Interactive browser preview on demo data — no desktop settings are changed</span>
</footer>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
<script src="studio/shared.js"></script>
<script src="app.js"></script>
</body>
</html>
`;

// The studio's own libraries for the browser studio: each .pragma library
// becomes a global namespace with its .imports passed in.
const libraries = [
    ["Catalog", "studio/StudioCatalog.js", []],
    ["Sections", "Sections.js", []],
    ["Format", "Format.js", []],
    ["Data", "diagram/DiagramData.js", []],
    ["DemoData", "DemoData.js", []],
    ["Probes", "Probes.js", []],
    ["SectionModels", "SectionModels.js", [["Sections", "Sections"], ["Format", "Format"], ["DiagramData", "Data"]]],
    ["Looks", "studio/Looks.js", []],
    ["Schema", "studio/Schema.js", [["Catalog", "Catalog"], ["Sections", "Sections"]]],
    ["Funding", "studio/ProjectFunding.js", []],
    ["License", "studio/ProjectLicense.js", []],
    ["Version", "studio/ProjectVersion.js", []],
    ["Project", "studio/ProjectInfo.js", [["Funding", "Funding"], ["License", "License"], ["Version", "Version"]]]
];
const modules = libraries.map(([name, file, imports]) => {
    const code = fs.readFileSync(path.join(ui, file), "utf8").replace(/^\.(pragma|import).*$/gm, "");
    const names = [...code.matchAll(/^(?:var|function)\s+([A-Za-z_$][\w$]*)/gm)].map(m => m[1]);
    const params = imports.map(i => i[0]).join(", ");
    const args = imports.map(i => "Glassy." + i[1]).join(", ");
    return `// ${file}\nGlassy.${name} = (function (${params}) {\n${code}\nreturn { ${[...new Set(names)].join(", ")} };\n})(${args});`;
}).join("\n\n");
// DiagramData.js asks QML's Qt.color for colour channels.
const qtShim = `var Qt = { color: function (c) {
    var s = String(c).replace("#", ""), a = 1;
    if (s.length === 3) s = s.split("").map(function (x) { return x + x; }).join("");
    if (s.length === 8) { a = parseInt(s.slice(0, 2), 16) / 255; s = s.slice(2); }
    var n = parseInt(s, 16);
    return { r: (n >> 16 & 255) / 255, g: (n >> 8 & 255) / 255, b: (n & 255) / 255, a: a };
} };`;
fs.mkdirSync(path.join(site, "studio"), { recursive: true });
fs.writeFileSync(path.join(site, "studio/shared.js"), `// Generated by tools/build_site.mjs from package/contents/ui. Do not edit.\n${qtShim}\nvar Glassy = {};\n${modules}\nGlassy.defaults = ${JSON.stringify(defaults)};\n`);

// The fragment shader as WebGL runs it: qsb's GLSL ES 100 variant.
const qsbFile = path.join(root, "package/contents/shaders/diagram.frag.qsb");
const esFile = path.join(site, "studio/diagram.frag");
try {
    const dump = execFileSync("qsb", ["--dump", qsbFile], { encoding: "utf8", maxBuffer: 1 << 24 });
    // qsb --dump prints each variant after a "Contents:" line and ends it
    // with a row of asterisks.
    const start = dump.indexOf("#version 100");
    const es = dump.slice(start).split("\n").reduce((acc, line) => acc.done || /^\*{5,}/.test(line) ? { ...acc, done: true } : { lines: acc.lines.concat([line]) }, { lines: [] }).lines.join("\n");
    fs.writeFileSync(esFile, es.trim() + "\n");
} catch (error) {
    if (!fs.existsSync(esFile))
        throw new Error("qsb is needed once to extract the shader: run make docs in the dev shell");
    console.log("docs: qsb not found, keeping " + path.relative(root, esFile));
}

// Wallpapers for the stage and preset cards, from the studio catalogue.
// QML writes #AARRGGBB, CSS reads #RRGGBBAA.
const cssColor = v => /^#[0-9a-f]{8}$/i.test(v) ? "#" + v.slice(3) + v.slice(1, 3) : v;
const theme = Object.entries(Catalog.StudioCatalog.theme).filter(([k]) => k !== "fontFamily").map(([k, v]) => `--studio-${k}:${cssColor(v)}`).join(";");
const wallpapers = Catalog.StudioCatalog.wallpapers.map(w => `.bd-${w.id}{background-color:${w.color};background-image:url("wallpapers/${w.file}")}`).join("\n");
fs.mkdirSync(path.join(site, "assets/studio/wallpapers"), { recursive: true });
fs.writeFileSync(path.join(site, "assets/studio/wallpapers.css"), `/* Generated by tools/build_site.mjs from the studio catalogue. */\n.bd{background-size:cover;background-position:center;background-repeat:no-repeat}\n:root{${theme}}\n${wallpapers}\n`);
for (const w of Catalog.StudioCatalog.wallpapers)
    fs.copyFileSync(path.join(ui, "studio/wallpapers", w.file), path.join(site, "assets/studio/wallpapers", w.file));
fs.copyFileSync(path.join(root, "package/icon.png"), path.join(site, "assets/studio/icon.png"));
fs.writeFileSync(path.join(site, "index.html"), html);
console.log("docs: wrote docs/website (index.html, studio/shared.js, studio/diagram.frag, wallpapers)");
